version: '3'
services:
  web:
    image: nginx:1.23.1
    #ホスト名を明示的に指定する
    hostname: web
    volumes:
      #設定ファイル(ローカルの相対パス:コンテナの絶対パス)
      - ./web/conf/:/etc/nginx/conf.d
      #ログ
      - ./web/log/:/var/log/nginx/
      - ./web/conf/uwsgi_params:/etc/nginx/uwsgi_params
      #staticファイル
      - ./static:/static
    ports:
      - "8000:8000" #ポート指定、ホスト:コンテナ
    depends_on:
      - back  #backに依存
    environment:
      TZ: "Asia/Tokyo"
    tty: true

  db:
    image: mariadb:10.8.3
    #ホスト名を明示的に指定する
    hostname: db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  #実行時のコマンド
    ports:
      - "3306:3306" #ポート指定、ホスト:コンテナ
    environment:  #コンテナ内の環境変数を指定
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/mysql/:/var/lib/mysql/
      - ./db/log/:/var/log/mysql/
    tty: true
  
  back:
    build: ./back
    #ホスト名を明示的に指定する
    hostname: back
    command: uwsgi --ini /etc/nginx/uwsgi.ini
    volumes: 
      - ./src:/opt/app
      - ./static:/static
      - ./web/uwsgi.ini:/etc/nginx/uwsgi.ini
      - ./back/log/:/var/log/uwsgi/
    expose:
      - "8001"
    depends_on:
      - db  #dbに依存
    environment:
      TZ: "Asia/Tokyo"
    tty: true

  front:
    build: ./front
    #ホスト名を明示的に指定する
    hostname: front
    ports:
      - "8080:8080"
    volumes:
      - ./front:/src
    #標準入力を開き続ける
    stdin_open: true
    tty: true